---
name: registripe_group
---
EventAttendee:
  extensions:
    - EventAttendeeGroupExtension

TicketSelection:
  extensions:
    - RegistrationGroupTicketSelectionExtension

TicketSelectionController:
  extensions:
    - RegistrationGroupTicketSelectionControllerExtension

RegistrationGroupTicketSelection:
  select_controller_action: group
  calculators:
    - GroupTicketSelection

EventRegisterController:
  extensions:
    - EventRegisterControllerGroupExtension
    
RegistrationGroupController:
  ticket_select_template: TicketCountSelections

RegistrationGroupEventTicket:
  selection_type: RegistrationGroupTicketSelection

